export const fromApiApplicant = (applicant) => ({
  id: applicant.id,
  lastName: applicant.lastName || '',
  firstName: applicant.firstName || '',
  middleName: applicant.middleName || '',
  extensionName: applicant.extensionName || '',
  birthday: applicant.birthdate || '',
  address: applicant.address || '',
  barangay: applicant.barangay || '',
  cityMunicipality: applicant.municipality || '',
  province: applicant.province || '',
  course: applicant.course || '',
  email: applicant.email || '',
  contactNo: applicant.contactNumber || '',
  sex: applicant.sex || '',
  civilStatus: applicant.civilStatus || '',
  age: applicant.age == null ? '' : String(applicant.age),
  remarks: applicant.remarks || '',
  gipForm: Boolean(applicant.requirements?.gipForm),
  resume: Boolean(applicant.requirements?.resume),
  validId: Boolean(applicant.requirements?.validId),
  psa: Boolean(applicant.requirements?.psa),
  diploma: Boolean(applicant.requirements?.diploma),
  tor: Boolean(applicant.requirements?.tor),
  supportingDocs: applicant.supportingDocuments || '',
  employmentStatus: applicant.classifications || [],
  dateApplied: applicant.dateApplied || '',
})

export const toApiApplicant = (applicant) => ({
  lastName: applicant.lastName,
  firstName: applicant.firstName,
  middleName: applicant.middleName,
  extensionName: applicant.extensionName,
  birthdate: applicant.birthday,
  age: applicant.age,
  sex: applicant.sex,
  civilStatus: applicant.civilStatus,
  address: applicant.address,
  barangay: applicant.barangay,
  municipality: applicant.cityMunicipality,
  province: applicant.province,
  course: applicant.course,
  email: applicant.email,
  contactNumber: applicant.contactNo,
  classifications: applicant.employmentStatus,
  dateApplied: applicant.dateApplied,
  remarks: applicant.remarks,
  requirements: {
    gipForm: applicant.gipForm,
    resume: applicant.resume,
    validId: applicant.validId,
    psa: applicant.psa,
    diploma: applicant.diploma,
    tor: applicant.tor,
  },
  supportingDocuments: applicant.supportingDocs,
})